### ISSUE TITLE
Not valid HTML

### ISSUE THREAD

**Issue by jomo** [ByNathan/jQuery.loadScroll#1]
```HTML
<img isrc="load-this-1.png">
```
Validated with [The W3C Markup Validation Service](http://validator.w3.org/check):

```HTML
Error: Attribute isrc not allowed on element img at this point.
Error: Element img is missing required attribute src.
```

I suggest using `data-src="load-this-1.png` and `src="#"` instead

**Comment by ByNathan** [comment]
@jomo Thanks. Keep an eye out for an update…
